#!/system/bin/sh
################################################################
# ------------------------------------------------------------ #
# |                        Pure Tweaks                       | #
# ------------------------------------------------------------ #
################################################################
#Interval between cleaner runs,in seconds, 86400=24 hours
RUN_EVERY=86400

#Cleaner
busybox rm -f /data/anr/*.*
busybox rm -f /data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/last_alog/*
busybox rm -f /data/last_kmsg/*
busybox rm -f /data/mlog/*
busybox rm -f /data/tombstones/*
busybox rm -f /data/system/dropbox/*
chmod 400 /data/system/dropbox
busybox rm -f /data/system/usagestats/*
busybox chmod 400 /data/system/usagestats

export sampling_rate=10000
export up_threshold=80
