#!/system/bin/sh
################################################################
# ------------------------------------------------------------ #
# |                        Pure Tweaks                       | #
# ------------------------------------------------------------ #
################################################################
# Spex@xda
# have in mind that lines that start with "#" are comments
# From Darky's zipalign - Modified to make it actually work by DeveDroid. 

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

busybox mount -o rw,remount /system;

for DIR in /system/app /data/app; do
	cd $DIR;
	for APK in *.apk; do
		if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
			echo "Already checked: $DIR/$APK" | tee -a $LOG_FILE;
		else
			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
			if [ $ZIPCHECK == "1" ]; then
				echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE;
				/system/xbin/zipalign -f 4 $APK /data/local/$APK;
				rc = "$?";
				if [ $rc -eq 0 ]; then
					if [ -e "/data/local/$APK" ]; then
						cp -f -p "/data/local/$APK" "$APK" | tee -a $LOG_FILE;
						rm -f "/data/local/$APK";
						grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
					else
						echo "ZipAligning $APK Failed (no output file)"  | tee -a $LOG_FILE;
					fi;
				else
					[ -f "/data/local/$APK" ] && rm -f "/data/local/$APK"
					echo "ZipAligning $APK Failed (rc: $rc)"  | tee -a $LOG_FILE;
				fi;
			else
				echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE;
				grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
			fi;
		fi;
	done;
done;

busybox mount -o ro,remount /system;
touch $ZIPALIGNDB;

# END OF TWEAKS
