#!/system/bin/sh
#

if [ ! -h /data/local/tmp/adreno_config.txt ]; then
    ln -s /system/etc/adreno_config.txt /data/local/tmp/adreno_config.txt
fi

echo NO_NORMALIZED_SLEEPER > /sys/kernel/debug/sched_features